server:
  port: 8081
spring:
  cloud:
    stream:
      kafka: #如果用的是rabbitMQ这里填 rabbit
        binder:
          brokers: 47.99.88.28:9092
          auto-create-topics: true
          replication-factor: 1
          producer-properties:
            acks: all
            max.block.ms: 60000
          transaction:
            transaction-id-prefix:  tx
            producer:
              retries: 2000
              acks: all
              requiredAcks: all
              enable:
               idempotence: true    
      bindings:
        order_output: #通道名称 对应代码中的 @Output(Source.OUTPUT)
          destination: order_topic #消息发往的目的地，对应topic
          group: order_group #对应kafka的group,防止重复消费
          content-type: application/json #消息的格式
          
          
    